package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AcquisitionRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AcquisitionRelationship extends org.gmod.gbol.simpleObject.generated.AbstractAcquisitionRelationship {

	private static final long serialVersionUID = 1L;

	public AcquisitionRelationship(){
		super();
	}
}
