package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.BiomaterialRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class BiomaterialRelationship extends org.gmod.gbol.simpleObject.generated.AbstractBiomaterialRelationship {

	private static final long serialVersionUID = 1L;

	public BiomaterialRelationship(){
		super();
	}
}
