package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Control.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Control extends org.gmod.gbol.simpleObject.generated.AbstractControl {

	private static final long serialVersionUID = 1L;

	public Control(){
		super();
	}
}
