package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CVTermProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CVTermProperty extends org.gmod.gbol.simpleObject.generated.AbstractCVTermProperty {

	private static final long serialVersionUID = 1L;

	public CVTermProperty(){
		super();
	}
}
