package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CVTermRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CVTermRelationship extends org.gmod.gbol.simpleObject.generated.AbstractCVTermRelationship {

	private static final long serialVersionUID = 1L;

	public CVTermRelationship(){
		super();
	}
}
