package org.gmod.gbol.simpleObject;

import org.gmod.gbol.simpleObject.CV;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CVTerm extends org.gmod.gbol.simpleObject.generated.AbstractCVTerm {

	private static final long serialVersionUID = 1L;

	public CVTerm(){
		super();
	}
	
	public CVTerm(String name,CV cv){
		this.setCv(cv);
        this.setName(name);
        this.setIsObsolete(0);
	}
}
