package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.EnvironmentCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class EnvironmentCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractEnvironmentCVTerm {

	private static final long serialVersionUID = 1L;

	public EnvironmentCVTerm(){
		super();
	}
}
