package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRange.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRange extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRange {

	private static final long serialVersionUID = 1L;

	public FeatureRange(){
		super();
	}
}
