package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeaturePublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeaturePublication extends org.gmod.gbol.simpleObject.generated.AbstractFeaturePublication {

	private static final long serialVersionUID = 1L;

	public FeaturePublication(){
		super();
	}
}
