package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureLocation.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureLocation extends org.gmod.gbol.simpleObject.generated.AbstractFeatureLocation {

	private static final long serialVersionUID = 1L;

	public FeatureLocation(){
		super();
	}
}
