package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibraryDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibraryDBXref extends org.gmod.gbol.simpleObject.generated.AbstractLibraryDBXref {

	private static final long serialVersionUID = 1L;

	public LibraryDBXref(){
		super();
	}
}
