package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Organism.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Organism extends org.gmod.gbol.simpleObject.generated.AbstractOrganism {

	private static final long serialVersionUID = 1L;

	public Organism(){
		super();
	}
}
