package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationProperty extends org.gmod.gbol.simpleObject.generated.AbstractPublicationProperty {

	private static final long serialVersionUID = 1L;

	public PublicationProperty(){
		super();
	}
}
