package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationDBXref extends org.gmod.gbol.simpleObject.generated.AbstractPublicationDBXref {

	private static final long serialVersionUID = 1L;

	public PublicationDBXref(){
		super();
	}
}
