package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationAuthor.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationAuthor extends org.gmod.gbol.simpleObject.generated.AbstractPublicationAuthor {

	private static final long serialVersionUID = 1L;

	public PublicationAuthor(){
		super();
	}
}
