package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Quantification.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Quantification extends org.gmod.gbol.simpleObject.generated.AbstractQuantification {

	private static final long serialVersionUID = 1L;

	public Quantification(){
		super();
	}
}
