package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockGenotype.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockGenotype extends org.gmod.gbol.simpleObject.generated.AbstractStockGenotype {

	private static final long serialVersionUID = 1L;

	public StockGenotype(){
		super();
	}
}
