package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockCollectionProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockCollectionProperty extends org.gmod.gbol.simpleObject.generated.AbstractStockCollectionProperty {

	private static final long serialVersionUID = 1L;

	public StockCollectionProperty(){
		super();
	}
}
