package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Treatment.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Treatment extends org.gmod.gbol.simpleObject.generated.AbstractTreatment {

	private static final long serialVersionUID = 1L;

	public Treatment(){
		super();
	}
}
