####
#### The bioentity description file for GOlr and AmiGO.
####
id: bbop_bio
description: A description of bioentities file for GOlr.
display_name: Bioentities
document_category: bioentity
weight: 30
boost_weights: bioentity^2.0 bioentity_label^2.0  isa_partof_closure_label^1.0 family_tag^1.0 family_tag_label^1.0
result_weights: bioentity^6.0 taxon^4.0 family_tag^3.0 type^2.0 db^1.0
filter_weights: db^7.0 type^6.0 family_tag_label^5.0 taxon_closure_label^4.0 isa_partof_closure_label^3.0
fields:
  - id: id
    description: Bioentity ID.
    display_name: Acc
    type: string
    property: []
  - id: bioentity
    description: Bioentity ID.
    display_name: Acc
    type: string
    property: []
  - id: bioentity_label
    description: Symbol or name.
    display_name: Label
    type: string
    property: []
    searchable: true
  - id: type
    description: "Column 12: type class id."
    display_name: Type class id
    type: string
    property: []
## Old code:
#   - id: type_label
#     description: "Column 12: type class label."
#     display_name: Type class label
#     type: string
#     property: []
#   - id: type_closure
#     description: "Derived from c12 + SO."
#     display_name: Type closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: type_closure_label
#     description: "Derived from c12 + SO."
#     display_name: Type label closure
#     type: string
#     cardinality: multi
#     property: []
  - id: taxon
    description: "Column 13: taxon."
    display_name: Taxon
    type: string
    property: []
  - id: taxon_label
    description: "Derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon
    type: string
    property: []
    searchable: true
  - id: taxon_closure
    description: "IDs derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon closure
    type: string
    cardinality: multi
    property: []
  - id: taxon_closure_label
    description: "Labels derived from C13 + ncbi_taxonomy.obo."
    display_name: Taxon closure (labels)
    type: string
    cardinality: multi
    property: []
    searchable: true
  - id: isa_partof_closure
    description: "Closure of ids/accs over isa and partof."
    display_name: Is-a/Part-of closure
    type: string
    cardinality: multi
    property: []
  - id: isa_partof_closure_label
    description: "Closure of labels over isa and partof."
    display_name: Is-a/Part-of closure (labels)
    type: string
    cardinality: multi
    property: []
    searchable: true
## Old code.
#   - id: regulates_closure
#     description: "Closure of ids/accs over regulates."
#     display_name: regulates closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: regulates_closure_label
#     description: "Closure of labels over regulates."
#     display_name: regulates label closure
#     type: string
#     cardinality: multi
#     property: []
  - id: db
    description: "Column 1: Identifier database."
    display_name: Database
    type: string
    property: []
## Old code.
#   - id: descriptive_name
#     description: Full name or name.
#     display_name: Full name
#     type: string
#     property: []
#     searchable: true
#   - id: synonym
#     description: Any synonym.
#     display_name: Synonym
#     type: string
#     cardinality: multi
#     property: []
#   - id: alternate_id
#     description: Any alternaitve id.
#     display_name: Alt id
#     type: string
#     cardinality: multi
#     property: []
#   - id: description
#     description: Definition.
#     display_name: Definition
#     type: string
#     property: []
#     searchable: true
#   - id: subset
#     description: Member of these named subsets.
#     display_name: Subset
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_obsolete
#     description: Is this obsolete?
#     display_name: Obsolete
#     type: integer
#     property: []
#   - id: comment
#     description: Comment.
#     display_name: comment
#     type: string
# #    cardinality: multi
#     property: []
#     searchable: true
#   - id: definition_xref
#     description: DBXref for definitions.
#     display_name: Def dbxref
#     type: string
#     cardinality: multi
#     property: []
#   - id: direct_annotation
#     description: Direct terms associatied with GP.
#     display_name: Direct annotations
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_closure
#     description: All terms associatied with GP.
#     display_name: All annotations
#     type: string
#     cardinality: multi
#     property: []
#   - id: axiom
#     description: "Each ontology entity (class or property) can be associated with multiple OWL axioms. We cache them in the index so that advanced OWL-aware clients can pull relevant information quickly. Axioms are stored in functional syntax."
#     display_name: Axiom
#     type: string
#     cardinality: multi
#     property: []
#   - id: bioentity_alternate_label
#     description: Alternate label.
#     display_name: Alternate label
#     type: string
#     cardinality: multi
#     property: []
#   - id: is_negated
#     description: Derived from column 4.
#     display_name: Is not
#     type: string
#     property: []
#   - id: qualifier
#     description: Derived from column 4.
#     display_name: Qualifier
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_class
#     description: Column 5.
#     display_name: Annotation class
#     type: string
#     property: []
#   - id: aspect
#     description: Column 9.
#     display_name: Ontology (aspect)
#     type: string
#     property: []
#   - id: annotation_class_label
#     description: "Column 5 + ontology."
#     display_name: Annotation class label
#     type: string
#     property: []
#   - id: secondary_taxon
#     description: Acts on taxon.
#     display_name: Secondary taxon
#     type: string
#     property: []
#   - id: secondary_taxon_label
#     description: Acts on taxon.
#     display_name: Secondary taxon label
#     type: string
#     property: []
#   - id: bioentity_isoform
#     description: ???
#     display_name: Bioentity isoform
#     type: string
#     cardinality: multi
#     property: []
#   - id: bioentity_isoform_label
#     description: ???
#     display_name: Bioentity isoform label
#     type: string
#     cardinality: multi
#     property: []
#   - id: evidence_type
#     description: ???
#     display_name: Evidence type
#     type: string
#     property: []
#   - id: evidence_closure
#     description: ???
#     display_name: Evidence closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: evidence_with
#     description: ???
#     display_name: Evidence with
#     type: string
#     cardinality: multi
#     property: []
#   - id: reference
#     description: ???
#     display_name: Reference
#     type: string
#     property: []
#   - id: annotation_extension_class
#     description: ???
#     display_name: Annotation extension class
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_extension_class_label
#     description: ???
#     display_name: Annotation extension class label
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_extension_class_closure
#     description: ???
#     display_name: Annotation extension class closure
#     type: string
#     cardinality: multi
#     property: []
#   - id: annotation_extension_class_closure_label
#     description: ???
#     display_name: Annotation extension class label closure
#     type: string
#     cardinality: multi
#     property: []
  - id: family_tag
    description: Family IDs that are associated with this entity.
    display_name: Family ID
    type: string
    cardinality: multi
    searchable: true
    property: []
  - id: family_tag_label
    description: Families that are associated with this entity.
    display_name: Family
    type: string
    cardinality: multi
    searchable: true
    property: []
  - id: phylo_graph
    description: JSON blob form of the phylogenic tree.
    display_name: This should not be displayed
    type: string
    property: []
    indexed: false
## TODO: Sleeping for now, but will re-add when the right
## experimental GAFs start getting loaded as well.
# - id: phylo_ancestor_closure
#   description: All phylogenic ancestor annotations to this entity.
#   display_name: Ancestor annotations
#   type: string
#   cardinality: multi
#   property: []
# - id: phylo_descendant_closure
#   description: All phylogenic descendant annotations to this entity.
#   display_name: Descendant annotations
#   type: string
#   cardinality: multi
#   property: []
