####
#### The ontology description file for GOlr and AmiGO.
####
id: bbop_ont
description: Test mapping of ontology class for GO.
display_name: Ontology
document_category: ontology_class
weight: 40
boost_weights: annotation_class^2.0 annotation_class_label^2.0 description^1.0 comment^0.5 synonym^1.0 alternate_id^1.0
result_weights: annotation_class^8.0 description^6.0 source^4.0 synonym^3.0 alternate_id^2.0 comment^1.0
filter_weights: source^4.0 subset^2.0 isa_partof_closure_label^1.0 is_obsolete^0.0
fields:
  - id: id
    description: Term acc/ID.
    display_name: Acc
    type: string
    property: [getIdentifier]
  - id: annotation_class
    description: Term acc/ID.
    display_name: Term ID
    type: string
    property: [getIdentifier]
  - id: annotation_class_label
    description: Common term name.
    display_name: Term
    type: string
    property: [getLabel]
    searchable: true
## Ever used with terms?
# - id: descriptive_name
#     description: Term description.
#     display_name: Description
#     type: string
#     property: [descriptive_name]
#    searchable: true
  - id: description
    description: Term definition.
    display_name: Definition
    type: string
    property: [getDef]
    searchable: true
  - id: source
    description: Term namespace.
    display_name: Source
    type: string
    property: [getNamespace]
  - id: is_obsolete
    description: Is the term obsolete?
    display_name: Obsoletion
    type: boolean
    property: [getIsObsoleteBinaryString]
  - id: comment
    description: Term comment.
    display_name: Comment
    type: string
    property: [getComment]
    searchable: true
## looks like single in OWLGraphWrapper API
#    cardinality: multi
  - id: synonym
    description: Term synonym.
    display_name: Synonym
    type: string
    property: [getOBOSynonymStrings]
    cardinality: multi
    searchable: true
  - id: alternate_id
    description: Alternate term id.
    display_name: Alt ID
    type: string
    property: [getAnnotationPropertyValues, alt_id]
    cardinality: multi
  - id: replaced_by
    description: Term that replaces this term.
    display_name: Replaced By
    type: string
    property: [getAnnotationPropertyValues, replaced_by]
    cardinality: multi
  - id: consider
    description: Others terms you might want to look at.
    display_name: Consider
    type: string
    property: [getAnnotationPropertyValues, consider]
    cardinality: multi
  - id: subset
    description: Term subset.
    display_name: Subset
    type: string
    property: [getSubsets]
    cardinality: multi
  - id: definition_xref
    description: Definition cross-reference.
    display_name: Def XRef
    type: string
    property: [getDefXref]
    cardinality: multi
  - id: isa_partof_closure
    description: "Closure of ids/accs over isa and partof."
    display_name: Is-a/Part-of closure
    type: string
    cardinality: multi
    property: [getIsaPartofIDClosure]
  - id: isa_partof_closure_label
    description: "Closure of labels over isa and partof."
    display_name: Is-a/Part-of closure (labels)
    type: string
    cardinality: multi
    property: [getIsaPartofLabelClosure]
    searchable: true
  - id: topology_graph
    description: JSON blob form of the local stepwise topology graph.
    display_name: This should not be displayed
    type: string
    property: [getSegmentShuntGraphJSON]
    indexed: false
  - id: transitivity_graph
    description: JSON blob form of the local relation transitivity graph.
    display_name: This should not be displayed
    type: string
    property: [getLineageShuntGraphJSON]
    indexed: false
