####
#### Use kwalify and this schema to validate the config files.
#### Examples:
####    kwalify -f schema.yaml ont-config.yaml
####    kwalify -f schema.yaml ann-config.yaml ann_ev_agg-config.yaml bio-config.yaml ont-config.yaml
####
type: map
mapping:
  "id":
    type: str
    required: yes
  "description":
    type: str
    required: yes
  "display_name":
    type: str
    required: yes
  "document_category":
    type: str
    required: yes
  "weight":
    type: int
    required: no
  "boost_weights":
    type: str
    required: no
  "filter_weights":
    type: str
    required: no
  "result_weights":
    type: str
    required: no
  "searchable_extension":
    type: str
    required: no
  "fields":
    type: seq
    sequence:
      - type: map
        mapping:
          "id":
            type: str
            required: yes
          "description":
            type: str
            required: yes
          "display_name":
            type: str
            required: yes
          "type":
            type: str
            required: yes 
          "required":
            type: bool
            required: no
          "cardinality":
            type: str
            required: no
          # "property":
          #   type: str
          #   required: yes
          "property":
            type: seq
            required: yes
            sequence:
              - type: str
          "transform":
            type: seq
            required: no
            sequence:
              - type: str
          "searchable":
            type: bool
            required: no
          "indexed":
            type: bool
            required: no
