---
name: GOBO-DBIC-GODBModel
version: 0.01
author:
  - 'Seth Carbon <sjcarbon@cpan.org>'
abstract: DBIC wrapper and related for the Gene Ontology database.
license: open_source
requires:
  DBIx::Class::Schema: 0
  Data::Dumper: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
