 % -- ********************************************************* --
 % -- Autogenerated Prolog factfiles 
 % -- see http://www.blipkit.org for details 
 % -- ********************************************************* --


 % -- Property/Slot --
property('ends_before_end_of').
metadata_db:entity_label('ends_before_end_of', 'ends_before_end_of').

 % -- Property/Slot --
property('starts_after_start_of').
metadata_db:entity_label('starts_after_start_of', 'starts_after_start_of').
holds_over_chain('starts_after_start_of', ['preceded_by','starts_after_start_of']).

 % -- Property/Slot --
property('during').
metadata_db:entity_label('during', 'during').
property_intersection_element('during', 'ends_before_end_of').
property_intersection_element('during', 'starts_after_start_of').

 % -- Property/Slot --
property('preceded_by').
metadata_db:entity_label('preceded_by', 'preceded_by').

class('embryogenesis').
restriction('embryogenesis', 'starts_after_start_of', 'lifecycle').

class('adult_stage').
restriction('adult_stage', 'ends_before_end_of', 'lifecycle').
restriction('adult_stage', 'preceded_by', 'embryogenesis').

class('lifecycle').

