 % -- ********************************************************* --
 % -- Autogenerated Prolog factfiles 
 % -- see http://www.blipkit.org for details 
 % -- ********************************************************* --


 % -- Property/Slot --
property('ends_before_end_of').
metadata_db:entity_label('ends_before_end_of', 'ends_before_end_of').

 % -- Property/Slot --
property('starts_after_start_of').
metadata_db:entity_label('starts_after_start_of', 'starts_after_start_of').

 % -- Property/Slot --
property('during').
metadata_db:entity_label('during', 'during').
property_intersection_element('during', 'ends_before_end_of').
property_intersection_element('during', 'starts_after_start_of').

class('gastrulation').
restriction('gastrulation', 'starts_after_start_of', 'lifecycle').
restriction('gastrulation', 'ends_before_end_of', 'lifecycle').

class('lifecycle').

