#!/usr/bin/perl -w
#!/usr/bin/perl -wT

####
####
#### A survey mouse rat and human annotation.
####
####

##
## reset; DBIC_TRACE = 1 ./report_1
##

BEGIN { require "config.pl"; }
use lib $ENV{GO_DEV_ROOT} . '/go-perl';
use lib $ENV{GO_DEV_ROOT} . '/go-db-perl';
use lib $ENV{GO_DEV_ROOT} . '/amigo/perl';

## Bring in necessaries.
use utf8;
use strict;
use Data::Dumper;
use AmiGO;
use GO::CGI::Utilities;

my $core = AmiGO->new();

my $apph = GO::CGI::Utilities::create_apph;
my $dbh = $apph->dbh;
my $complete_query = <<SQL;
SELECT   gene_product.symbol,   gene_product.full_name,   dbxref.xref_dbname,   dbxref.xref_key,   species.genus,   species.species,   association.is_not,   evidence.code,   direct_term.acc AS direct_acc,   direct_term.name AS direct_name, ancestor_term.acc AS ancestor_acc, ancestor_term.name AS ancestor_name, graph_path.distance FROM   gene_product    INNER JOIN dbxref ON (gene_product.dbxref_id=dbxref.id) INNER JOIN species ON (gene_product.species_id=species.id)    INNER JOIN association ON (gene_product.id=association.gene_product_id)    INNER JOIN evidence ON (association.id=evidence.association_id)    INNER JOIN term AS direct_term ON (association.term_id=direct_term.id)   INNER JOIN graph_path ON (direct_term.id=graph_path.term2_id) INNER JOIN term AS ancestor_term ON (ancestor_term.id=graph_path.term1_id) WHERE NOT ancestor_term.name = 'all' AND (species.ncbi_taxa_id = 9606 || species.ncbi_taxa_id = 10090 || species.ncbi_taxa_id = 10116 )
SQL

$core->kvetch($complete_query);
my $sth = $dbh->prepare($complete_query)
  or die "Couldn't prepare statement: " . $dbh->errstr;
$sth->execute()
  or die "Couldn't execute statement: " . $sth->errstr;

##
while( my @row = $sth->fetchrow_array() ){

#   my $symbol        = $row[0];
#   my $full_name     = $row[1];
#   my $xref_dbname   = $row[2];
#   my $xref_key      = $row[3];
#   my $genus         = $row[4];
#   my $species       = $row[5];
#   my $is_not        = $row[6];
#   my $code          = $row[7];
#   my $direct_acc    = $row[8];
#   my $direct_name   = $row[9];
#   my $ancestor_acc  = $row[10];
#   my $ancestor_name = $row[11];
#   my $distance      = $row[12];

  my $print_str = join "\t", @row;
  print $print_str . "\n";
}

