/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java */

package org.bbop.expression.parser;

import org.bbop.expression.JexlContext;

public class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /** {@inheritDoc} */
  public Object value(JexlContext jc) throws Exception {
      throw new BreakLoopException();
  }
}
