#!/bin/sh
APPDIR=`dirname $0`;

external=''

for name in external/*.jar
  do
	external=$external:$name
done


java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-mac.jar$external" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.bbop.RefGenome/RefGenome.html;

#java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Users/siddharthabasu/Documents/Projects/Support/gwt-mac-1.5.0/gwt-user.jar:/Users/siddharthabasu/Documents/Projects/Support/gwt-mac-1.5.0/gwt-dev-mac.jar:$APPDIR/external/gxt.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.bbop.RefGenome/RefGenome.html;
