package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CV.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CV extends org.gmod.gbol.simpleObject.generated.AbstractCV {

	private static final long serialVersionUID = 1L;

	public CV(){
		super();
	}
	
	public CV(String cvName){
		super(cvName);
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		// TODO Auto-generated method stub
		return null;
	}
}
