package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.DB.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class DB extends org.gmod.gbol.simpleObject.generated.AbstractDB {

	private static final long serialVersionUID = 1L;

	public DB(){
		super();
	}
	
	public DB(String db) {
		super(db);
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		// TODO Auto-generated method stub
		return null;
	}
}
