package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.DBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class DBXref extends org.gmod.gbol.simpleObject.generated.AbstractDBXref {

	private static final long serialVersionUID = 1L;

	public DBXref(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getDb().getWriteObjects());
		
		// Multiples
		for (DBXrefProperty dbxp : this.getDbxrefProperties())
			writeObjects.addAll(dbxp.getWriteObjects());

		return writeObjects;
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{
		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int db = 1;
			public static final int dbxrefprops = 2;
		}
		
		public SimpleObjectIterator(DBXref dbxref)
		{
			super(dbxref);
		}

		public AbstractSimpleObject next()
		{
			DBXref dbxref = (DBXref)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processSingletonIterator(Status.db, dbxref.getDb());
			}
			else {
				retVal = soIter.next();
				if (status == Status.db) {
					processCollectionIterators(Status.dbxrefprops, dbxref.getDbxrefProperties());
				}
				if (status == Status.dbxrefprops) {
					processLastCollectionIterator();
				}
			}
			current = retVal;
			return retVal;
		}
	}
}
