package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.DBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class DBXref extends org.gmod.gbol.simpleObject.generated.AbstractDBXref {

	private static final long serialVersionUID = 1L;

	public DBXref(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getDb().getWriteObjects());
		
		// Multiples
		for (DBXrefProperty dbxp : this.getDbxrefProperties())
			writeObjects.addAll(dbxp.getWriteObjects());

		return writeObjects;
	}
}
