package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Element.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Element extends org.gmod.gbol.simpleObject.generated.AbstractElement {

	private static final long serialVersionUID = 1L;

	public Element(){
		super();
	}
}
