package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Environment.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Environment extends org.gmod.gbol.simpleObject.generated.AbstractEnvironment {

	private static final long serialVersionUID = 1L;

	public Environment(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Multiples
		for (EnvironmentCVTerm ecvt : this.getEnvironmentCVTerms())
			writeObjects.addAll(ecvt.getWriteObjects());
		
		return writeObjects;
	}
}
