package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ExpressionCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ExpressionCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractExpressionCVTerm {

	private static final long serialVersionUID = 1L;

	public ExpressionCVTerm(){
		super();
	}
}
