package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationship extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationship {

	private static final long serialVersionUID = 1L;

	public FeatureRelationship(){
		super();
	}
	
	/** Copy constructor.  Does a shallow copy from the source FeatureRelationship.
	 * 
	 * @param src - FeatureRelationship to copy the data from
	 */
	public FeatureRelationship(FeatureRelationship src)
	{
		setType(src.getType());
		setObjectFeature(src.getObjectFeature());
		setSubjectFeature(src.getSubjectFeature());
		setValue(src.getValue());
		setRank(src.getRank());
		setFeatureRelationshipProperties(src.getFeatureRelationshipProperties());
		setFeatureRelationshipPublications(src.getFeatureRelationshipPublications());
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getType().getWriteObjects());
		writeObjects.addAll(this.getSubjectFeature().getWriteObjects());
		writeObjects.addAll(this.getObjectFeature().getWriteObjects());
		
		// Multiples
		for (FeatureRelationshipProperty frprop : this.getFeatureRelationshipProperties())
			writeObjects.addAll(frprop.getWriteObjects());
		for (FeatureRelationshipPublication frpub : this.getFeatureRelationshipPublications())
			writeObjects.addAll(frpub.getWriteObjects());
		
		return writeObjects;
	}
}
