package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureDBXref extends org.gmod.gbol.simpleObject.generated.AbstractFeatureDBXref {

	private static final long serialVersionUID = 1L;

	public FeatureDBXref(){
		super();
	}
}
