package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractFeatureCVTerm {

	private static final long serialVersionUID = 1L;

	public FeatureCVTerm(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getCvterm().getWriteObjects());
		writeObjects.addAll(this.getPublication().getWriteObjects());

		// Multiples
		for (FeatureCVTermProperty fcvtprop : this.getFeatureCVTermProperties())
			writeObjects.addAll(fcvtprop.getWriteObjects());
		for (FeatureCVTermPublication fcvtpub : this.getFeatureCVTermPublications())
			writeObjects.addAll(fcvtpub.getWriteObjects());
		for (FeatureCVTermDBXref fcvtdbx : this.getFeatureCVTermDBXrefs())
			writeObjects.addAll(fcvtdbx.getWriteObjects());
		
		return writeObjects;
	}
}
