package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureLocation.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureLocation extends org.gmod.gbol.simpleObject.generated.AbstractFeatureLocation {

	private static final long serialVersionUID = 1L;

	public FeatureLocation(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getSourceFeature().getWriteObjects()); // Won't traverse; srcfeatures shouldn't loop
		
		// Multiples
		for (FeatureLocationPublication flp : this.getFeatureLocationPublications())
			writeObjects.addAll(flp.getWriteObjects());
		
		return writeObjects;
	}
}
