package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationshipProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationshipProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationshipProperty {

	private static final long serialVersionUID = 1L;

	public FeatureRelationshipProperty(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getType().getWriteObjects());
		
		// Multiples
		for (FeatureRelationshipPropertyPublication frpp : this.getFeatureRelationshipPropertyPublications())
			writeObjects.addAll(frpp.getWriteObjects());
		
		return writeObjects;
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{
		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int type = 1;
			public static final int featureRelationshipPropPubs = 2;
		}
				
		public SimpleObjectIterator(FeatureRelationshipProperty featureRelationshipProp)
		{
			super(featureRelationshipProp);
		}

		public AbstractSimpleObject next()
		{
			FeatureRelationshipProperty featureRelationshipProp = (FeatureRelationshipProperty)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processSingletonIterator(Status.type, featureRelationshipProp.getType());
			}
			else {
				retVal = soIter.next();
				if (status == Status.type) {
					processCollectionIterators(Status.featureRelationshipPropPubs,
							featureRelationshipProp.getFeatureRelationshipPropertyPublications());
				}
				else if (status == Status.featureRelationshipPropPubs) {
					processLastCollectionIterator();
				}
			}
			current = retVal;
			return retVal;
		}

	}
	
}
