package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeaturePosition.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeaturePosition extends org.gmod.gbol.simpleObject.generated.AbstractFeaturePosition {

	private static final long serialVersionUID = 1L;

	public FeaturePosition(){
		super();
	}
}
