package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeaturePhenotype.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeaturePhenotype extends org.gmod.gbol.simpleObject.generated.AbstractFeaturePhenotype {

	private static final long serialVersionUID = 1L;

	public FeaturePhenotype(){
		super();
	}
}
