package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibraryPublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibraryPublication extends org.gmod.gbol.simpleObject.generated.AbstractLibraryPublication {

	private static final long serialVersionUID = 1L;

	public LibraryPublication(){
		super();
	}
}
