package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Organism.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Organism extends org.gmod.gbol.simpleObject.generated.AbstractOrganism {

	private static final long serialVersionUID = 1L;

	public Organism(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
				
		// Multiples
		for (OrganismProperty op : this.getOrganismProperties())
			writeObjects.addAll(op.getWriteObjects());
		for (OrganismDBXref odbx : this.getOrganismDBXrefs())
			writeObjects.addAll(odbx.getWriteObjects());
		
		return writeObjects;
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}
	
	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int organismProps = 1;
			public static final int organismDbxrefs = 2;
		}
		
		public SimpleObjectIterator(Organism organism)
		{
			super(organism);
		}

		public AbstractSimpleObject next()
		{
			Organism organism = (Organism)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processCollectionIterators(Status.organismProps, organism.getOrganismProperties());
			}
			else {
				retVal = soIter.next();
				if (status == Status.organismProps) {
					processCollectionIterators(Status.organismDbxrefs, organism.getOrganismDBXrefs());
				}
				if (status == Status.organismDbxrefs) {
					processLastCollectionIterator();
				}
			}
			current = retVal;
			return retVal;
		}

	}

}
