package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.OrganismDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class OrganismDBXref extends org.gmod.gbol.simpleObject.generated.AbstractOrganismDBXref {

	private static final long serialVersionUID = 1L;

	public OrganismDBXref(){
		super();
	}
}
