package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Organism.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Organism extends org.gmod.gbol.simpleObject.generated.AbstractOrganism {

	private static final long serialVersionUID = 1L;

	public Organism(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
				
		// Multiples
		for (OrganismProperty op : this.getOrganismProperties())
			writeObjects.addAll(op.getWriteObjects());
		for (OrganismDBXref odbx : this.getOrganismDBXrefs())
			writeObjects.addAll(odbx.getWriteObjects());
		
		return writeObjects;
	}
}
