package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.OrganismProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class OrganismProperty extends org.gmod.gbol.simpleObject.generated.AbstractOrganismProperty {

	private static final long serialVersionUID = 1L;

	public OrganismProperty(){
		super();
	}
}
