package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.OrganismProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class OrganismProperty extends org.gmod.gbol.simpleObject.generated.AbstractOrganismProperty {

	private static final long serialVersionUID = 1L;

	public OrganismProperty(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		// TODO Auto-generated method stub
		return null;
	}
}
