package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Phenotype.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Phenotype extends org.gmod.gbol.simpleObject.generated.AbstractPhenotype {

	private static final long serialVersionUID = 1L;

	public Phenotype(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getAttribute().getWriteObjects());
		writeObjects.addAll(this.getAssay().getWriteObjects());
		writeObjects.addAll(this.getCvalue().getWriteObjects());
		writeObjects.addAll(this.getObservable().getWriteObjects());

		// Multiples
		for (PhenotypeCVTerm pcvt : this.getPhenotypeCVTerms())
			writeObjects.addAll(pcvt.getWriteObjects());
		
		// Specifically not traversing PhenotypeStatements, since that 
		// could involve us in a loop or a very long traversal

		return writeObjects;	
	}
}
