package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhenotypeDescription.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhenotypeDescription extends org.gmod.gbol.simpleObject.generated.AbstractPhenotypeDescription {

	private static final long serialVersionUID = 1L;

	public PhenotypeDescription(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		// TODO Auto-generated method stub
		return null;
	}
}
