package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticTreePublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticTreePublication extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticTreePublication {

	private static final long serialVersionUID = 1L;

	public PhylogeneticTreePublication(){
		super();
	}
}
