package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationDBXref extends org.gmod.gbol.simpleObject.generated.AbstractPublicationDBXref {

	private static final long serialVersionUID = 1L;

	public PublicationDBXref(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);
		
		// Singletons
		writeObjects.addAll(this.getDbxref().getWriteObjects());
		
		return writeObjects;
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}

	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{

		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public final static int dbxref = 1;
		}
	
		public SimpleObjectIterator(PublicationDBXref pubDbxref)
		{
			super(pubDbxref);
		}
		
		public AbstractSimpleObject next()
		{
			PublicationDBXref pubDbxref = (PublicationDBXref)object;
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				processSingletonIterator(Status.dbxref, pubDbxref.getDbxref());
			}
			else {
				if (status == Status.dbxref) {
					retVal = soIter.next();
				}
			}
			current = retVal;
			return retVal;
		}
	}
	
}
