package org.gmod.gbol.simpleObject;

import java.util.ArrayList;
import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationAuthor.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationAuthor extends org.gmod.gbol.simpleObject.generated.AbstractPublicationAuthor {

	private static final long serialVersionUID = 1L;

	public PublicationAuthor(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		ArrayList<AbstractSimpleObject> writeObjects = new ArrayList<AbstractSimpleObject>();
		// Have to write yourself
		writeObjects.add(this);

		return writeObjects;
	}

	public AbstractSimpleObjectIterator getWriteableObjects()
	{
		return new SimpleObjectIterator(this);
	}
	
	private static class SimpleObjectIterator extends AbstractSimpleObjectIterator
	{
				
		private static class Status extends AbstractSimpleObjectIterator.Status
		{
			public static final int done = 1;
		}
		
		public SimpleObjectIterator(PublicationAuthor pubAuthor)
		{
			super(pubAuthor);
		}

		public AbstractSimpleObject next()
		{
			AbstractSimpleObject retVal = null;
			if (status == Status.self) {
				retVal = peek();
				status = Status.done;
			}
			current = retVal;
			return retVal;
		}
	}

}
