package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockCollectionStock.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockCollectionStock extends org.gmod.gbol.simpleObject.generated.AbstractStockCollectionStock {

	private static final long serialVersionUID = 1L;

	public StockCollectionStock(){
		super();
	}
}
