package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StudyProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StudyProperty extends org.gmod.gbol.simpleObject.generated.AbstractStudyProperty {

	private static final long serialVersionUID = 1L;

	public StudyProperty(){
		super();
	}
}
