package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StudyPropertyFeature.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StudyPropertyFeature extends org.gmod.gbol.simpleObject.generated.AbstractStudyPropertyFeature {

	private static final long serialVersionUID = 1L;

	public StudyPropertyFeature(){
		super();
	}
}
