package org.gmod.gbol.simpleObject;

import java.util.Collection;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Synonym.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Synonym extends org.gmod.gbol.simpleObject.generated.AbstractSynonym {

	private static final long serialVersionUID = 1L;

	public Synonym(){
		super();
	}

	@Override
	public Collection<AbstractSimpleObject> getWriteObjects() {
		// TODO Auto-generated method stub
		return null;
	}
}
