package org.gmod.gbol.simpleObject.${pojo.getMetaAsString("chadoModule")};

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.${pojo.getDeclarationName()}.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ${pojo.getDeclarationName()} extends org.gmod.gbol.simpleObject.generated.${pojo.getDeclarationName()} {

	private static final long serialVersionUID = 1L;

}
