/* Generated By:JJTree: Do not edit this line. ASTFunctionDefinitions.java */

package org.bbop.expression.parser;

public class ASTFunctionDefinitions extends SimpleNode {
  public ASTFunctionDefinitions(int id) {
    super(id);
  }

  public ASTFunctionDefinitions(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
