/* Generated By:JJTree: Do not edit this line. ASTGenusExpression.java */

package org.obo.postcomp;

import org.apache.log4j.*;

public class ASTGenusExpression extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTGenusExpression.class);
  public ASTGenusExpression(int id) {
    super(id);
  }

  public ASTGenusExpression(OBOPostcomp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OBOPostcompVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
