/* Generated By:JJTree: Do not edit this line. ASTPostcompExpression.java */

package org.obo.postcomp;

import org.apache.log4j.*;

public class ASTPostcompExpression extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTPostcompExpression.class);
  public ASTPostcompExpression(int id) {
    super(id);
  }

  public ASTPostcompExpression(OBOPostcomp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OBOPostcompVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
