/* Generated By:JJTree: Do not edit this line. ./OBOPostcompVisitor.java */

package org.obo.postcomp;

public interface OBOPostcompVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPostcompExpression node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTGenusExpression node, Object data);
  public Object visit(ASTDifferentiaExpression node, Object data);
  public Object visit(ASTCompoundExpression node, Object data);
}
