#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256m -cp "$APPDIR/src:$APPDIR/bin:/Users/sid/Documents/Projects/Reference_Genome_DB/Software/Libraries/GWT/gwt-user.jar:/Users/sid/Documents/Projects/Reference_Genome_DB/Software/Libraries/GWT/gwt-dev-mac.jar:lib/mygwt.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.bbop.RefGenome;
