/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java */

package org.bbop.expression.parser;

import org.bbop.expression.JexlContext;

import org.apache.log4j.*;

public class ASTBreakStatement extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTBreakStatement.class);
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /** {@inheritDoc} */
  @Override
public Object value(JexlContext jc) throws Exception {
      throw new BreakLoopException();
  }
}
