/* Generated By:JJTree: Do not edit this line. ASTExtendedParamIdentifier.java */

package org.bbop.expression.parser;

import org.bbop.expression.JexlContext;

import org.apache.log4j.*;

public class ASTExtendedParamIdentifier extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTExtendedParamIdentifier.class);
  public ASTExtendedParamIdentifier(int id) {
    super(id);
  }

  public ASTExtendedParamIdentifier(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public Object value(JexlContext jc) throws Exception {
	  ASTIdentifier id = (ASTIdentifier) jjtGetChild(0);
	  return id.val;
  }
}
