/* Generated By:JJTree: Do not edit this line. ASTGlobalTag.java */

package org.bbop.expression.parser;

public class ASTGlobalTag extends SimpleNode {
  public ASTGlobalTag(int id) {
    super(id);
  }

  public ASTGlobalTag(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
