/* Generated By:JJTree: Do not edit this line. ASTImportStatement.java */

package org.bbop.expression.parser;

import org.apache.log4j.*;

public class ASTImportStatement extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTImportStatement.class);
  public ASTImportStatement(int id) {
    super(id);
  }

  public ASTImportStatement(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
