/* Generated By:JJTree: Do not edit this line. ASTPreDecrementNode.java */

package org.bbop.expression.parser;

import org.bbop.expression.ExpressionException;
import org.bbop.expression.JexlContext;
import org.bbop.expression.util.Coercion;

import org.apache.log4j.*;

public class ASTPreDecrementNode extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTPreDecrementNode.class);
  public ASTPreDecrementNode(int id) {
    super(id);
  }

  public ASTPreDecrementNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /** {@inheritDoc} */
  @Override
public Object value(JexlContext context) throws Exception {
      // left should be the variable (reference) to assign to
      SimpleNode left = (SimpleNode) jjtGetChild(0);
      Integer val = null;
      try {
    	  val = new Integer(Coercion.coerceInteger(left.value(context)).intValue() - 1);
      } catch (Exception ex) {
    	  throw new ParseException("Can't use decrement operator on non-integer");
      }
      
      ASTReference reference = (ASTReference) jjtGetChild(0);
      left = (SimpleNode) reference.jjtGetChild(0);
      if (left instanceof ASTIdentifier) {
          String identifier = ((ASTIdentifier) left)
                  .getIdentifierString();
          
          try {
        	  context.setVariable(identifier, val);
          } catch (ExpressionException ex) {
        	  ex.decorateException(this);
          }
      }
      return val;
  }
}
