/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

package org.bbop.expression.parser;

import org.bbop.expression.JexlContext;

import org.apache.log4j.*;

public class ASTReturnStatement extends SimpleNode {

	//initialize logger
	protected final static Logger logger = Logger.getLogger(ASTReturnStatement.class);
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /** {@inheritDoc} */
  @Override
public Object value(JexlContext jc) throws Exception {
      SimpleNode arg = (SimpleNode) jjtGetChild(0);
      throw new ReturnValueException(arg.value(jc));
  }
}
