/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.bbop.expression.parser;

public interface ParserConstants {

  int EOF = 0;
  int COMMENT = 1;
  int LINE_COMMENT = 7;
  int BLOCK_COMMENT = 8;
  int INTEGER_LITERAL = 9;
  int FLOAT_LITERAL = 10;
  int IDENTIFIER = 69;
  int LETTER = 70;
  int DIGIT = 71;
  int STRING_LITERAL = 72;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"empty\"",
    "\"(\"",
    "\")\"",
    "\"size\"",
    "\"=\"",
    "\"||\"",
    "\"or\"",
    "\"&&\"",
    "\"and\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\"<\"",
    "\"lt\"",
    "\">\"",
    "\"gt\"",
    "\"<=\"",
    "\"le\"",
    "\">=\"",
    "\"ge\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"%\"",
    "\"mod\"",
    "\"~\"",
    "\"!\"",
    "\"not\"",
    "\"++\"",
    "\"--\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"global\"",
    "\"function\"",
    "\",\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"foreach\"",
    "\"in\"",
    "\"for\"",
    "\"return \"",
    "\"break\"",
    "\"export\"",
    "\"import\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
  };

}
