#!/usr/bin/perl -w
####
#### A version of GOOSE that is more integrated with the rest
#### of AmiGO. Will eventually replace the current standalone
#### version in amigo/amigo/cgi-bin.
####

BEGIN { require "config.pl"; }
use lib $ENV{GO_ROOT} . '/go-perl';
use lib $ENV{GO_ROOT} . '/go-db-perl';
use lib $ENV{GO_ROOT} . '/amigo/perl';
#use lib $ENV{GO_SVN_ROOT} . '/gobo-dbic';
#use AmiGO;

use AmiGO::WebApp::GOOSE;
my $goose = AmiGO::WebApp::GOOSE->new(PARAMS => {});
$goose->run();
