#!/usr/bin/perl -w
####
#### ...
####

BEGIN { require "config.pl"; }
use lib $ENV{GO_ROOT} . '/go-perl';
use lib $ENV{GO_ROOT} . '/go-db-perl';
use lib $ENV{GO_ROOT} . '/amigo/perl';

use AmiGO::WebApp::XPTermRequest;
my $xptrc = AmiGO::WebApp::XPTermRequest->new(PARAMS => {});
$xptrc->run();
