package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AssayProject.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AssayProject extends org.gmod.gbol.simpleObject.generated.AbstractAssayProject {

	private static final long serialVersionUID = 1L;

	public AssayProject(){
		super();
	}
}
