package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Channel.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Channel extends org.gmod.gbol.simpleObject.generated.AbstractChannel {

	private static final long serialVersionUID = 1L;

	public Channel(){
		super();
	}
}
