package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ContactRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ContactRelationship extends org.gmod.gbol.simpleObject.generated.AbstractContactRelationship {

	private static final long serialVersionUID = 1L;

	public ContactRelationship(){
		super();
	}
}
