package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CVTermDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CVTermDBXref extends org.gmod.gbol.simpleObject.generated.AbstractCVTermDBXref {

	private static final long serialVersionUID = 1L;

	public CVTermDBXref(){
		super();
	}
}
