package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Environment.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Environment extends org.gmod.gbol.simpleObject.generated.AbstractEnvironment {

	private static final long serialVersionUID = 1L;

	public Environment(){
		super();
	}
}
