package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeatureProperty {

	private static final long serialVersionUID = 1L;

	public FeatureProperty(){
		super();
	}
}
