package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibraryCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibraryCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractLibraryCVTerm {

	private static final long serialVersionUID = 1L;

	public LibraryCVTerm(){
		super();
	}
}
