package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticNodeDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticNodeDBXref extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticNodeDBXref {

	private static final long serialVersionUID = 1L;

	public PhylogeneticNodeDBXref(){
		super();
	}
}
