package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StudyFactorValue.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StudyFactorValue extends org.gmod.gbol.simpleObject.generated.AbstractStudyFactorValue {

	private static final long serialVersionUID = 1L;

	public StudyFactorValue(){
		super();
	}
}
