package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StudyAssay.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StudyAssay extends org.gmod.gbol.simpleObject.generated.AbstractStudyAssay {

	private static final long serialVersionUID = 1L;

	public StudyAssay(){
		super();
	}
}
