#!/usr/bin/perl -w

##
## Early test for session server.
##

use strict;
use IO::Socket;

my($server, $port, $n) = @ARGV;

my $client = IO::Socket::INET->new(
				   Proto    => 'tcp',
				   PeerAddr => $server,
				   PeerPort => $port
				   #timeout => "1" # it appears that
				   # this was for
				   # handshaking only
				  ) or die "Can't connect to $server:$port\n";

## TODO: use alarm as timeout for connection wait
## TODO: why can't get complete output?

$client->autoflush(1);
print $client "$n\n";
my $factors = <$client>;
print $factors;
