package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AnalysisFeature.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AnalysisFeature extends org.gmod.gbol.simpleObject.generated.AbstractAnalysisFeature {

	private static final long serialVersionUID = 1L;

}
