package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AnalysisProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AnalysisProperty extends org.gmod.gbol.simpleObject.generated.AbstractAnalysisProperty {

	private static final long serialVersionUID = 1L;

}
