package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ArrayDesignProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ArrayDesignProperty extends org.gmod.gbol.simpleObject.generated.AbstractArrayDesignProperty {

	private static final long serialVersionUID = 1L;

	public ArrayDesignProperty(){
		super();
	}
}
