package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ArrayDesign.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ArrayDesign extends org.gmod.gbol.simpleObject.generated.AbstractArrayDesign {

	private static final long serialVersionUID = 1L;

}
