package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AssayProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AssayProperty extends org.gmod.gbol.simpleObject.generated.AbstractAssayProperty {

	private static final long serialVersionUID = 1L;

}
