package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Assay.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Assay extends org.gmod.gbol.simpleObject.generated.AbstractAssay {

	private static final long serialVersionUID = 1L;

}
