package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.AssayBiomaterial.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class AssayBiomaterial extends org.gmod.gbol.simpleObject.generated.AbstractAssayBiomaterial {

	private static final long serialVersionUID = 1L;

}
