package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Biomaterial.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Biomaterial extends org.gmod.gbol.simpleObject.generated.AbstractBiomaterial {

	private static final long serialVersionUID = 1L;

}
