package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.BiomaterialProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class BiomaterialProperty extends org.gmod.gbol.simpleObject.generated.AbstractBiomaterialProperty {

	private static final long serialVersionUID = 1L;

}
