package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.BiomaterialDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class BiomaterialDBXref extends org.gmod.gbol.simpleObject.generated.AbstractBiomaterialDBXref {

	private static final long serialVersionUID = 1L;

}
