package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.BiomaterialTreatment.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class BiomaterialTreatment extends org.gmod.gbol.simpleObject.generated.AbstractBiomaterialTreatment {

	private static final long serialVersionUID = 1L;

}
