package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Contact.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Contact extends org.gmod.gbol.simpleObject.generated.AbstractContact {

	private static final long serialVersionUID = 1L;

}
