package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CV.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CV extends org.gmod.gbol.simpleObject.generated.AbstractCV {

	private static final long serialVersionUID = 1L;
	
	public CV(String name){
		super(name);
	}

}
