package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.CVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class CVTerm extends org.gmod.gbol.simpleObject.generated.AbstractCVTerm {

	private static final long serialVersionUID = 1L;
	
	public CVTerm(String name,CV cv, int isObsolete ){
		this.setCv(cv);
        this.setName(name);
        this.setIsObsolete(isObsolete);
	}

	
}
