package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.DB.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class DB extends org.gmod.gbol.simpleObject.generated.AbstractDB {

	public DB(String db) {
		super(db);
	}

	private static final long serialVersionUID = 1L;

}
