package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.DBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class DBXref extends org.gmod.gbol.simpleObject.generated.AbstractDBXref {

	private static final long serialVersionUID = 1L;

}
