package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.EImage.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class EImage extends org.gmod.gbol.simpleObject.generated.AbstractEImage {

	private static final long serialVersionUID = 1L;

}
