package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ElementResultRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ElementResultRelationship extends org.gmod.gbol.simpleObject.generated.AbstractElementResultRelationship {

	private static final long serialVersionUID = 1L;

}
