package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ElementResult.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ElementResult extends org.gmod.gbol.simpleObject.generated.AbstractElementResult {

	private static final long serialVersionUID = 1L;

}
