package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ElementRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ElementRelationship extends org.gmod.gbol.simpleObject.generated.AbstractElementRelationship {

	private static final long serialVersionUID = 1L;

}
