package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ExpressionImage.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ExpressionImage extends org.gmod.gbol.simpleObject.generated.AbstractExpressionImage {

	private static final long serialVersionUID = 1L;

}
