package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Expression.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Expression extends org.gmod.gbol.simpleObject.generated.AbstractExpression {

	private static final long serialVersionUID = 1L;

}
