package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.ExpressionCVTermProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class ExpressionCVTermProperty extends org.gmod.gbol.simpleObject.generated.AbstractExpressionCVTermProperty {

	private static final long serialVersionUID = 1L;

}
