package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureLocationPublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureLocationPublication extends org.gmod.gbol.simpleObject.generated.AbstractFeatureLocationPublication {

	private static final long serialVersionUID = 1L;

}
