package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractFeatureCVTerm {

	private static final long serialVersionUID = 1L;

}
