package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureExpressionProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureExpressionProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeatureExpressionProperty {

	private static final long serialVersionUID = 1L;

	public FeatureExpressionProperty(){
		super();
	}
}
