package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeaturePublicationProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeaturePublicationProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeaturePublicationProperty {

	private static final long serialVersionUID = 1L;

}
