package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationshipProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationshipProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationshipProperty {

	private static final long serialVersionUID = 1L;

}
