package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationship extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationship {

	private static final long serialVersionUID = 1L;

}
