package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureSynonym.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureSynonym extends org.gmod.gbol.simpleObject.generated.AbstractFeatureSynonym {

	private static final long serialVersionUID = 1L;

}
