package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureRelationshipPropertyPublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureRelationshipPropertyPublication extends org.gmod.gbol.simpleObject.generated.AbstractFeatureRelationshipPropertyPublication {

	private static final long serialVersionUID = 1L;

}
