package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureExpression.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureExpression extends org.gmod.gbol.simpleObject.generated.AbstractFeatureExpression {

	private static final long serialVersionUID = 1L;

}
