package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureCVTermProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureCVTermProperty extends org.gmod.gbol.simpleObject.generated.AbstractFeatureCVTermProperty {

	private static final long serialVersionUID = 1L;

}
