package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.FeatureMap.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class FeatureMap extends org.gmod.gbol.simpleObject.generated.AbstractFeatureMap {

	private static final long serialVersionUID = 1L;

}
