package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Genotype.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Genotype extends org.gmod.gbol.simpleObject.generated.AbstractGenotype {

	private static final long serialVersionUID = 1L;

}
