package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibraryFeature.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibraryFeature extends org.gmod.gbol.simpleObject.generated.AbstractLibraryFeature {

	private static final long serialVersionUID = 1L;

}
