package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Library.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Library extends org.gmod.gbol.simpleObject.generated.AbstractLibrary {

	private static final long serialVersionUID = 1L;

}
