package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibrarySynonym.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibrarySynonym extends org.gmod.gbol.simpleObject.generated.AbstractLibrarySynonym {

	private static final long serialVersionUID = 1L;

}
