package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.LibraryProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class LibraryProperty extends org.gmod.gbol.simpleObject.generated.AbstractLibraryProperty {

	private static final long serialVersionUID = 1L;

	public LibraryProperty(){
		super();
	}
}
