package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.MAGEDocumentation.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class MAGEDocumentation extends org.gmod.gbol.simpleObject.generated.AbstractMAGEDocumentation {

	private static final long serialVersionUID = 1L;

	public MAGEDocumentation(){
		super();
	}
}
