package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhenotypeStatement.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhenotypeStatement extends org.gmod.gbol.simpleObject.generated.AbstractPhenotypeStatement {

	private static final long serialVersionUID = 1L;

}
