package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhenotypeCVTerm.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhenotypeCVTerm extends org.gmod.gbol.simpleObject.generated.AbstractPhenotypeCVTerm {

	private static final long serialVersionUID = 1L;

}
