package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticNodePublication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticNodePublication extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticNodePublication {

	private static final long serialVersionUID = 1L;

}
