package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticNodeProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticNodeProperty extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticNodeProperty {

	private static final long serialVersionUID = 1L;

}
