package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticNodeOrganism.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticNodeOrganism extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticNodeOrganism {

	private static final long serialVersionUID = 1L;

}
