package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PhylogeneticNodeRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PhylogeneticNodeRelationship extends org.gmod.gbol.simpleObject.generated.AbstractPhylogeneticNodeRelationship {

	private static final long serialVersionUID = 1L;

}
