package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Project.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Project extends org.gmod.gbol.simpleObject.generated.AbstractProject {

	private static final long serialVersionUID = 1L;

}
