package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Publication.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Publication extends org.gmod.gbol.simpleObject.generated.AbstractPublication {

	private static final long serialVersionUID = 1L;

}
