package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.PublicationRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class PublicationRelationship extends org.gmod.gbol.simpleObject.generated.AbstractPublicationRelationship {

	private static final long serialVersionUID = 1L;

}
