package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockDBXref.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockDBXref extends org.gmod.gbol.simpleObject.generated.AbstractStockDBXref {

	private static final long serialVersionUID = 1L;

}
