package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockProperty extends org.gmod.gbol.simpleObject.generated.AbstractStockProperty {

	private static final long serialVersionUID = 1L;

}
