package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Stock.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Stock extends org.gmod.gbol.simpleObject.generated.AbstractStock {

	private static final long serialVersionUID = 1L;

}
