package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StockRelationship.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StockRelationship extends org.gmod.gbol.simpleObject.generated.AbstractStockRelationship {

	private static final long serialVersionUID = 1L;

}
