package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.StudyDesignProperty.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class StudyDesignProperty extends org.gmod.gbol.simpleObject.generated.AbstractStudyDesignProperty {

	private static final long serialVersionUID = 1L;

}
