package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.Synonym.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class Synonym extends org.gmod.gbol.simpleObject.generated.AbstractSynonym {

	private static final long serialVersionUID = 1L;

}
