package org.gmod.gbol.simpleObject;

/*
 * Autogenerated extension of org.gmod.gbol.simpleObject.generated.TableInfo.
 * Add custom code to this file. 
 *
 * Author: Robert Bruggner, rbruggner@berkeleybop.org
 *
*/

public class TableInfo extends org.gmod.gbol.simpleObject.generated.AbstractTableInfo {

	private static final long serialVersionUID = 1L;

}
