/* Generated By:JJTree: Do not edit this line. ASTCompoundExpression.java */

package org.obo.postcomp;

public class ASTCompoundExpression extends SimpleNode {
  public ASTCompoundExpression(int id) {
    super(id);
  }

  public ASTCompoundExpression(OBOPostcomp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OBOPostcompVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
