/* Generated By:JJTree: Do not edit this line. ASTPostcompExpression.java */

package org.obo.postcomp;

public class ASTPostcompExpression extends SimpleNode {
  public ASTPostcompExpression(int id) {
    super(id);
  }

  public ASTPostcompExpression(OBOPostcomp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OBOPostcompVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
