/* Generated By:JJTree: Do not edit this line. ./OBOPostcompTreeConstants.java */

package org.obo.postcomp;

public interface OBOPostcompTreeConstants
{
  public int JJTPOSTCOMPEXPRESSION = 0;
  public int JJTIDENTIFIER = 1;
  public int JJTVOID = 2;
  public int JJTGENUSEXPRESSION = 3;
  public int JJTDIFFERENTIAEXPRESSION = 4;
  public int JJTCOMPOUNDEXPRESSION = 5;


  public String[] jjtNodeName = {
    "PostcompExpression",
    "Identifier",
    "void",
    "GenusExpression",
    "DifferentiaExpression",
    "CompoundExpression",
  };
}
