/* Generated By:JJTree&JavaCC: Do not edit this line. OBOPostcompConstants.java */
package org.obo.postcomp;

public interface OBOPostcompConstants {

  int EOF = 0;
  int IDENTIFIER = 5;
  int LETTER = 6;
  int DIGIT = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"^\"",
  };

}
