#!/usr/bin/ruby
####
#### Simple script for testing BrowserID.
####

require 'cgi' 
require 'erb' # templating
require 'mechanize' # http client
require 'json' # parse the client's response

## Page template, contains embedded JS, shoul
page_template = %{
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>A Secret Guarded by BrowserID</title>
  <script src="https://browserid.org/include.js"
          type="text/javascript"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"
          type="text/javascript"></script>
  <script type="text/javascript">
     jQuery(document).ready(function(){
       jQuery("#login-button").click(function(event){
         event.preventDefault();
         // This function comes from https://browserid.org/include.js.
         // If the user successfully supplies an email address (and thus)
         // an assertion, we'll send it to our server so we can check it
         // out and get user data out of it if it's okay.
         navigator.id.getVerifiedEmail(function(assertion) {
           if( assertion ){
              window.location.href =
               "http://accordion.lbl.gov/cgi-bin/browserid/secret?assertion=" + assertion;
           }else{
             alert("Keep trying! The secret is amazing!");
           }
         });
       });
     });
   </script>
 </head>
 <body>

  <% if okay_p %>

  <p>Too late, <b><%= user_id %></b>--it's escaping!</p>
  <p><img src="http://accordion.lbl.gov/browserid/secret.jpg" /></p>

  <% else %>

  <p>Login to see a secret...</p>
  <p><img id="login-button" src="http://accordion.lbl.gov/browserid/sign_in_blue.png" /></p>

  <% end %>

 </body>
</html>
}.gsub(/^  /, '')
page_skeleton = ERB.new(page_template, 0, "%<>")

## Add a convenience method to CGI.
class CGI
  def take field, default
    if self.has_key?(field)
      self[field]
    else
      default
    end
  end
end

## Get the incoming variables and set the defaults.
cgi = CGI.new
assertion = cgi.take('assertion', nil)
okay_p = nil
user_id = 'a good user id (email) should go here'

## Take the incoming assertion and see if it checks out with one of
## the online providers.
if assertion

  ## Get the response from the authority.
  authority = "https://browserid.org/verify"
  audience = "accordion.lbl.gov"
  agent = Mechanize.new
  response =
    agent.post(authority, {'assertion' => assertion, 'audience' => audience})

  ## Check our response, and if it's okay, send the information back
  ## to the page.
  if response.nil? == false && response.code == '200'
    response_json = response.content
    response_data = JSON.parse(response_json)
    if response_data['status'] == 'okay'
      okay_p = true
      user_id = response_data['email']
    end
  end
end

# ## For template: timer_p and question_p
# ## Convert incoming strings to useful variables.
# timer_p = timer.eql?('no') ? nil : true
#okay_p = question.eql?('no') ? nil : true

## Output.
cgi.out {
  page_skeleton.result
}
