#!/usr/bin/perl -w

####
#### Simple wrapper.
####

BEGIN { require "config.pl"; }
use lib $ENV{GO_ROOT} . '/go-perl';
use lib $ENV{GO_ROOT} . '/go-db-perl';
use lib $ENV{GO_ROOT} . '/amigo/perl';
use lib $ENV{GO_SVN_ROOT} . '/gobo-dbic';
use AmiGO;

use AmiGO::WebApp::Services;
my $amigo = AmiGO::WebApp::Services->new(PARAMS => {});
$amigo->run();
