#!/usr/bin/perl -w
##
## A CGI script to help tune the web-based benchmarking.
##

use strict;
use utf8;

## Set up CGI environment,
use CGI qw/:standard/;
use CGI::Carp qw(warningsToBrowser fatalsToBrowser);
$CGI::POST_MAX = 0;	## no uploads.
my $q = new CGI;

## Constants.
my $NUMBER_OF_SECONDS_TO_WAIT = 0;

my $time = $q->param('time');
if( $time && $time =~ /^[0-9]+$/ ){
  $NUMBER_OF_SECONDS_TO_WAIT = $time + 0; # can never remember when
                                          # coersion is needed
}

##
sleep($NUMBER_OF_SECONDS_TO_WAIT);

print<<EOC
content-type:text/html

<html>
 <body>
  <p>

I slept for $NUMBER_OF_SECONDS_TO_WAIT second(s)!

  </p>
 <body>
</html>
EOC
