#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/sjcarbon/local/src/svn/geneontology/go-dev/gwt/gwt-user.jar:/home/sjcarbon/local/src/svn/geneontology/go-dev/gwt/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.bbop.AmiGO;
