package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * AllOnlyRelationship generated by hbm2java
 */
public class AllOnlyRelationship implements java.io.Serializable {

	private AllOnlyRelationshipId id;

	public AllOnlyRelationship() {
	}

	public AllOnlyRelationship(AllOnlyRelationshipId id) {
		this.id = id;
	}

	public AllOnlyRelationshipId getId() {
		return this.id;
	}

	public void setId(AllOnlyRelationshipId id) {
		this.id = id;
	}

}
