package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * AllOnlyRelationship generated by hbm2java
 */
public class AllOnlyRelationship implements java.io.Serializable {

	private AllOnlyRelationshipId id;

	public AllOnlyRelationship() {
	}

	public AllOnlyRelationship(AllOnlyRelationshipId id) {
		this.id = id;
	}

	public AllOnlyRelationshipId getId() {
		return this.id;
	}

	public void setId(AllOnlyRelationshipId id) {
		this.id = id;
	}

}
