package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * AllSomeRelationship generated by hbm2java
 */
public class AllSomeRelationship implements java.io.Serializable {

	private AllSomeRelationshipId id;

	public AllSomeRelationship() {
	}

	public AllSomeRelationship(AllSomeRelationshipId id) {
		this.id = id;
	}

	public AllSomeRelationshipId getId() {
		return this.id;
	}

	public void setId(AllSomeRelationshipId id) {
		this.id = id;
	}

}
