package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * AnnotationAssertion generated by hbm2java
 */
public class AnnotationAssertion implements java.io.Serializable {

	private AnnotationAssertionId id;

	public AnnotationAssertion() {
	}

	public AnnotationAssertion(AnnotationAssertionId id) {
		this.id = id;
	}

	public AnnotationAssertionId getId() {
		return this.id;
	}

	public void setId(AnnotationAssertionId id) {
		this.id = id;
	}

}
