package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * AnnotationAssertion generated by hbm2java
 */
public class AnnotationAssertion extends GOModel implements java.io.Serializable {

	private Relation relation;
	private String obj;
	private String targetObj;
	private Ontology ontology;

	public AnnotationAssertion() {
		String keys[] = {"relation", "obj", "targetObj", "ontology"};
		this.initUniqueConstraintFields(AnnotationAssertion.class, keys);
	}

	public AnnotationAssertion(Relation relation, String obj, String targetObj,
			Ontology ontology) {
		this();
		this.relation = relation;
		this.obj = obj;
		this.targetObj = targetObj;
		this.ontology = ontology;
	}

	public Relation getRelation() {
		return this.relation;
	}

	public void setRelation(Relation relation) {
		this.relation = relation;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getTargetObj() {
		return this.targetObj;
	}

	public void setTargetObj(String targetObj) {
		this.targetObj = targetObj;
	}

	public Ontology getOntology() {
		return this.ontology;
	}

	public void setOntology(Ontology ontology) {
		this.ontology = ontology;
	}

}
