package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ClsIntersectionOf generated by hbm2java
 */
public class ClsIntersectionOf implements java.io.Serializable {

	private ClsIntersectionOfId id;

	public ClsIntersectionOf() {
	}

	public ClsIntersectionOf(ClsIntersectionOfId id) {
		this.id = id;
	}

	public ClsIntersectionOfId getId() {
		return this.id;
	}

	public void setId(ClsIntersectionOfId id) {
		this.id = id;
	}

}
