package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ClsUnionOf generated by hbm2java
 */
public class ClsUnionOf implements java.io.Serializable {

	private ClsUnionOfId id;

	public ClsUnionOf() {
	}

	public ClsUnionOf(ClsUnionOfId id) {
		this.id = id;
	}

	public ClsUnionOfId getId() {
		return this.id;
	}

	public void setId(ClsUnionOfId id) {
		this.id = id;
	}

}
