package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * DisjointWith generated by hbm2java
 */
public class DisjointWith implements java.io.Serializable {

	private DisjointWithId id;

	public DisjointWith() {
	}

	public DisjointWith(DisjointWithId id) {
		this.id = id;
	}

	public DisjointWithId getId() {
		return this.id;
	}

	public void setId(DisjointWithId id) {
		this.id = id;
	}

}
