package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * DisjointWithId generated by hbm2java
 */
public class DisjointWithId implements java.io.Serializable {

	private String cls;
	private String disjointCls;
	private String ontology;

	public DisjointWithId() {
	}

	public DisjointWithId(String cls, String disjointCls, String ontology) {
		this.cls = cls;
		this.disjointCls = disjointCls;
		this.ontology = ontology;
	}

	public String getCls() {
		return this.cls;
	}

	public void setCls(String cls) {
		this.cls = cls;
	}

	public String getDisjointCls() {
		return this.disjointCls;
	}

	public void setDisjointCls(String disjointCls) {
		this.disjointCls = disjointCls;
	}

	public String getOntology() {
		return this.ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DisjointWithId))
			return false;
		DisjointWithId castOther = (DisjointWithId) other;

		return ((this.getCls() == castOther.getCls()) || (this.getCls() != null
				&& castOther.getCls() != null && this.getCls().equals(
				castOther.getCls())))
				&& ((this.getDisjointCls() == castOther.getDisjointCls()) || (this
						.getDisjointCls() != null
						&& castOther.getDisjointCls() != null && this
						.getDisjointCls().equals(castOther.getDisjointCls())))
				&& ((this.getOntology() == castOther.getOntology()) || (this
						.getOntology() != null
						&& castOther.getOntology() != null && this
						.getOntology().equals(castOther.getOntology())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCls() == null ? 0 : this.getCls().hashCode());
		result = 37
				* result
				+ (getDisjointCls() == null ? 0 : this.getDisjointCls()
						.hashCode());
		result = 37 * result
				+ (getOntology() == null ? 0 : this.getOntology().hashCode());
		return result;
	}

}
