package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * EquivalentTo generated by hbm2java
 */
public class EquivalentTo implements java.io.Serializable {

	private EquivalentToId id;

	public EquivalentTo() {
	}

	public EquivalentTo(EquivalentToId id) {
		this.id = id;
	}

	public EquivalentToId getId() {
		return this.id;
	}

	public void setId(EquivalentToId id) {
		this.id = id;
	}

}
