package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * InferredRelationship generated by hbm2java
 */
public class InferredRelationship implements java.io.Serializable {

	private InferredRelationshipId id;

	public InferredRelationship() {
	}

	public InferredRelationship(InferredRelationshipId id) {
		this.id = id;
	}

	public InferredRelationshipId getId() {
		return this.id;
	}

	public void setId(InferredRelationshipId id) {
		this.id = id;
	}

}
