package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * NeverSomeRelationship generated by hbm2java
 */
public class NeverSomeRelationship implements java.io.Serializable {

	private NeverSomeRelationshipId id;

	public NeverSomeRelationship() {
	}

	public NeverSomeRelationship(NeverSomeRelationshipId id) {
		this.id = id;
	}

	public NeverSomeRelationshipId getId() {
		return this.id;
	}

	public void setId(NeverSomeRelationshipId id) {
		this.id = id;
	}

}
