package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjAlternateLabel generated by hbm2java
 */
public class ObjAlternateLabel implements java.io.Serializable {

	private ObjAlternateLabelId id;

	public ObjAlternateLabel() {
	}

	public ObjAlternateLabel(ObjAlternateLabelId id) {
		this.id = id;
	}

	public ObjAlternateLabelId getId() {
		return this.id;
	}

	public void setId(ObjAlternateLabelId id) {
		this.id = id;
	}

}
