package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjAlternateId generated by hbm2java
 */
public class ObjAlternateId implements java.io.Serializable {

	private ObjAlternateIdId id;

	public ObjAlternateId() {
	}

	public ObjAlternateId(ObjAlternateIdId id) {
		this.id = id;
	}

	public ObjAlternateIdId getId() {
		return this.id;
	}

	public void setId(ObjAlternateIdId id) {
		this.id = id;
	}

}
