package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjAlternateLabelId generated by hbm2java
 */
public class ObjAlternateLabelId implements java.io.Serializable {

	private String obj;
	private String label;
	private String synonymScope;
	private String synonymType;
	private String synonymXref;

	public ObjAlternateLabelId() {
	}

	public ObjAlternateLabelId(String obj, String label, String synonymScope,
			String synonymType, String synonymXref) {
		this.obj = obj;
		this.label = label;
		this.synonymScope = synonymScope;
		this.synonymType = synonymType;
		this.synonymXref = synonymXref;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getSynonymScope() {
		return this.synonymScope;
	}

	public void setSynonymScope(String synonymScope) {
		this.synonymScope = synonymScope;
	}

	public String getSynonymType() {
		return this.synonymType;
	}

	public void setSynonymType(String synonymType) {
		this.synonymType = synonymType;
	}

	public String getSynonymXref() {
		return this.synonymXref;
	}

	public void setSynonymXref(String synonymXref) {
		this.synonymXref = synonymXref;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjAlternateLabelId))
			return false;
		ObjAlternateLabelId castOther = (ObjAlternateLabelId) other;

		return ((this.getObj() == castOther.getObj()) || (this.getObj() != null
				&& castOther.getObj() != null && this.getObj().equals(
				castOther.getObj())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getSynonymScope() == castOther.getSynonymScope()) || (this
						.getSynonymScope() != null
						&& castOther.getSynonymScope() != null && this
						.getSynonymScope().equals(castOther.getSynonymScope())))
				&& ((this.getSynonymType() == castOther.getSynonymType()) || (this
						.getSynonymType() != null
						&& castOther.getSynonymType() != null && this
						.getSynonymType().equals(castOther.getSynonymType())))
				&& ((this.getSynonymXref() == castOther.getSynonymXref()) || (this
						.getSynonymXref() != null
						&& castOther.getSynonymXref() != null && this
						.getSynonymXref().equals(castOther.getSynonymXref())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getObj() == null ? 0 : this.getObj().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37
				* result
				+ (getSynonymScope() == null ? 0 : this.getSynonymScope()
						.hashCode());
		result = 37
				* result
				+ (getSynonymType() == null ? 0 : this.getSynonymType()
						.hashCode());
		result = 37
				* result
				+ (getSynonymXref() == null ? 0 : this.getSynonymXref()
						.hashCode());
		return result;
	}

}
