package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjDefinitionXref generated by hbm2java
 */
public class ObjDefinitionXref implements java.io.Serializable {

	private ObjDefinitionXrefId id;

	public ObjDefinitionXref() {
	}

	public ObjDefinitionXref(ObjDefinitionXrefId id) {
		this.id = id;
	}

	public ObjDefinitionXrefId getId() {
		return this.id;
	}

	public void setId(ObjDefinitionXrefId id) {
		this.id = id;
	}

}
