package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjDefinitionXrefId generated by hbm2java
 */
public class ObjDefinitionXrefId implements java.io.Serializable {

	private String obj;
	private String xref;

	public ObjDefinitionXrefId() {
	}

	public ObjDefinitionXrefId(String obj, String xref) {
		this.obj = obj;
		this.xref = xref;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getXref() {
		return this.xref;
	}

	public void setXref(String xref) {
		this.xref = xref;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjDefinitionXrefId))
			return false;
		ObjDefinitionXrefId castOther = (ObjDefinitionXrefId) other;

		return ((this.getObj() == castOther.getObj()) || (this.getObj() != null
				&& castOther.getObj() != null && this.getObj().equals(
				castOther.getObj())))
				&& ((this.getXref() == castOther.getXref()) || (this.getXref() != null
						&& castOther.getXref() != null && this.getXref()
						.equals(castOther.getXref())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getObj() == null ? 0 : this.getObj().hashCode());
		result = 37 * result
				+ (getXref() == null ? 0 : this.getXref().hashCode());
		return result;
	}

}
