package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjDefinitionXref generated by hbm2java
 */
public class ObjDefinitionXref extends GOModel implements java.io.Serializable {

	private String obj;
	private String xref;

	public ObjDefinitionXref() {
		String keys[] = {"obj", "xref"};
		this.initUniqueConstraintFields(ObjDefinitionXref.class, keys);
	}

	public ObjDefinitionXref(String obj, String xref) {
		this.obj = obj;
		this.xref = xref;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getXref() {
		return this.xref;
	}

	public void setXref(String xref) {
		this.xref = xref;
	}

}
