package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjSubsetId generated by hbm2java
 */
public class ObjSubsetId implements java.io.Serializable {

	private String obj;
	private String ontologySubset;

	public ObjSubsetId() {
	}

	public ObjSubsetId(String obj, String ontologySubset) {
		this.obj = obj;
		this.ontologySubset = ontologySubset;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getOntologySubset() {
		return this.ontologySubset;
	}

	public void setOntologySubset(String ontologySubset) {
		this.ontologySubset = ontologySubset;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjSubsetId))
			return false;
		ObjSubsetId castOther = (ObjSubsetId) other;

		return ((this.getObj() == castOther.getObj()) || (this.getObj() != null
				&& castOther.getObj() != null && this.getObj().equals(
				castOther.getObj())))
				&& ((this.getOntologySubset() == castOther.getOntologySubset()) || (this
						.getOntologySubset() != null
						&& castOther.getOntologySubset() != null && this
						.getOntologySubset().equals(
								castOther.getOntologySubset())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getObj() == null ? 0 : this.getObj().hashCode());
		result = 37
				* result
				+ (getOntologySubset() == null ? 0 : this.getOntologySubset()
						.hashCode());
		return result;
	}

}
