package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjSubset generated by hbm2java
 */
public class ObjSubset implements java.io.Serializable {

	private ObjSubsetId id;

	public ObjSubset() {
	}

	public ObjSubset(ObjSubsetId id) {
		this.id = id;
	}

	public ObjSubsetId getId() {
		return this.id;
	}

	public void setId(ObjSubsetId id) {
		this.id = id;
	}

}
