package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjXref generated by hbm2java
 */
public class ObjXref implements java.io.Serializable {

	private ObjXrefId id;

	public ObjXref() {
	}

	public ObjXref(ObjXrefId id) {
		this.id = id;
	}

	public ObjXrefId getId() {
		return this.id;
	}

	public void setId(ObjXrefId id) {
		this.id = id;
	}

}
