package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * ObjXrefId generated by hbm2java
 */
public class ObjXrefId implements java.io.Serializable {

	private String obj;
	private String xref;
	private String xrefDescription;

	public ObjXrefId() {
	}

	public ObjXrefId(String obj, String xref, String xrefDescription) {
		this.obj = obj;
		this.xref = xref;
		this.xrefDescription = xrefDescription;
	}

	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public String getXref() {
		return this.xref;
	}

	public void setXref(String xref) {
		this.xref = xref;
	}

	public String getXrefDescription() {
		return this.xrefDescription;
	}

	public void setXrefDescription(String xrefDescription) {
		this.xrefDescription = xrefDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjXrefId))
			return false;
		ObjXrefId castOther = (ObjXrefId) other;

		return ((this.getObj() == castOther.getObj()) || (this.getObj() != null
				&& castOther.getObj() != null && this.getObj().equals(
				castOther.getObj())))
				&& ((this.getXref() == castOther.getXref()) || (this.getXref() != null
						&& castOther.getXref() != null && this.getXref()
						.equals(castOther.getXref())))
				&& ((this.getXrefDescription() == castOther
						.getXrefDescription()) || (this.getXrefDescription() != null
						&& castOther.getXrefDescription() != null && this
						.getXrefDescription().equals(
								castOther.getXrefDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getObj() == null ? 0 : this.getObj().hashCode());
		result = 37 * result
				+ (getXref() == null ? 0 : this.getXref().hashCode());
		result = 37
				* result
				+ (getXrefDescription() == null ? 0 : this.getXrefDescription()
						.hashCode());
		return result;
	}

}
