package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * OntologyImports generated by hbm2java
 */
public class OntologyImports extends GOModel implements java.io.Serializable {

	private String ontology;
	private String importsOntology;

	public OntologyImports() {
		String keys[] = {"ontology", "importsOntology"};
		this.initUniqueConstraintFields(OntologyImports.class, keys);
	}

	public OntologyImports(String ontology, String importsOntology) {
		this();
		this.ontology = ontology;
		this.importsOntology = importsOntology;
	}

	public String getOntology() {
		return this.ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public String getImportsOntology() {
		return this.importsOntology;
	}

	public void setImportsOntology(String importsOntology) {
		this.importsOntology = importsOntology;
	}

}
