package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * OntologyAnnotationId generated by hbm2java
 */
public class OntologyAnnotationId implements java.io.Serializable {

	private String ontology;
	private String property;
	private String annotationValue;

	public OntologyAnnotationId() {
	}

	public OntologyAnnotationId(String ontology, String property,
			String annotationValue) {
		this.ontology = ontology;
		this.property = property;
		this.annotationValue = annotationValue;
	}

	public String getOntology() {
		return this.ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	public String getAnnotationValue() {
		return this.annotationValue;
	}

	public void setAnnotationValue(String annotationValue) {
		this.annotationValue = annotationValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OntologyAnnotationId))
			return false;
		OntologyAnnotationId castOther = (OntologyAnnotationId) other;

		return ((this.getOntology() == castOther.getOntology()) || (this
				.getOntology() != null && castOther.getOntology() != null && this
				.getOntology().equals(castOther.getOntology())))
				&& ((this.getProperty() == castOther.getProperty()) || (this
						.getProperty() != null
						&& castOther.getProperty() != null && this
						.getProperty().equals(castOther.getProperty())))
				&& ((this.getAnnotationValue() == castOther
						.getAnnotationValue()) || (this.getAnnotationValue() != null
						&& castOther.getAnnotationValue() != null && this
						.getAnnotationValue().equals(
								castOther.getAnnotationValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOntology() == null ? 0 : this.getOntology().hashCode());
		result = 37 * result
				+ (getProperty() == null ? 0 : this.getProperty().hashCode());
		result = 37
				* result
				+ (getAnnotationValue() == null ? 0 : this.getAnnotationValue()
						.hashCode());
		return result;
	}

}
