package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * OntologySubset generated by hbm2java
 */
public class OntologySubset extends GOModel implements java.io.Serializable {

	private String id;
	private String label;

	public OntologySubset() {
		String keys[] = {"id"};
		
		this.initUniqueConstraintFields(OntologySubset.class, keys);
		
	}

	public OntologySubset(String id) {
		this();
		this.id = id;
	}

	public OntologySubset(String id, String label) {
		this();
		this.id = id;
		this.label = label;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
