package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * OntologyImports generated by hbm2java
 */
public class OntologyImports implements java.io.Serializable {

	private OntologyImportsId id;

	public OntologyImports() {
	}

	public OntologyImports(OntologyImportsId id) {
		this.id = id;
	}

	public OntologyImportsId getId() {
		return this.id;
	}

	public void setId(OntologyImportsId id) {
		this.id = id;
	}

}
