package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Ontology generated by hbm2java
 */
public class Ontology implements java.io.Serializable {

	private String id;
	private String label;
	private String versioniri;
	private String creationDate;

	public Ontology() {
	}

	public Ontology(String id) {
		this.id = id;
	}

	public Ontology(String id, String label, String versioniri,
			String creationDate) {
		this.id = id;
		this.label = label;
		this.versioniri = versioniri;
		this.creationDate = creationDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getVersioniri() {
		return this.versioniri;
	}

	public void setVersioniri(String versioniri) {
		this.versioniri = versioniri;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

}
