package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * OntologySubset generated by hbm2java
 */
public class OntologySubset implements java.io.Serializable {

	private String id;
	private String label;

	public OntologySubset() {
	}

	public OntologySubset(String id) {
		this.id = id;
	}

	public OntologySubset(String id, String label) {
		this.id = id;
		this.label = label;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
