package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * RelationChainId generated by hbm2java
 */
public class RelationChainId implements java.io.Serializable {

	private String inferredRelation;
	private String relation1;
	private String relation2;
	private Boolean isBidirectional;

	public RelationChainId() {
	}

	public RelationChainId(String inferredRelation, String relation1,
			String relation2, Boolean isBidirectional) {
		this.inferredRelation = inferredRelation;
		this.relation1 = relation1;
		this.relation2 = relation2;
		this.isBidirectional = isBidirectional;
	}

	public String getInferredRelation() {
		return this.inferredRelation;
	}

	public void setInferredRelation(String inferredRelation) {
		this.inferredRelation = inferredRelation;
	}

	public String getRelation1() {
		return this.relation1;
	}

	public void setRelation1(String relation1) {
		this.relation1 = relation1;
	}

	public String getRelation2() {
		return this.relation2;
	}

	public void setRelation2(String relation2) {
		this.relation2 = relation2;
	}

	public Boolean getIsBidirectional() {
		return this.isBidirectional;
	}

	public void setIsBidirectional(Boolean isBidirectional) {
		this.isBidirectional = isBidirectional;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelationChainId))
			return false;
		RelationChainId castOther = (RelationChainId) other;

		return ((this.getInferredRelation() == castOther.getInferredRelation()) || (this
				.getInferredRelation() != null
				&& castOther.getInferredRelation() != null && this
				.getInferredRelation().equals(castOther.getInferredRelation())))
				&& ((this.getRelation1() == castOther.getRelation1()) || (this
						.getRelation1() != null
						&& castOther.getRelation1() != null && this
						.getRelation1().equals(castOther.getRelation1())))
				&& ((this.getRelation2() == castOther.getRelation2()) || (this
						.getRelation2() != null
						&& castOther.getRelation2() != null && this
						.getRelation2().equals(castOther.getRelation2())))
				&& ((this.getIsBidirectional() == castOther
						.getIsBidirectional()) || (this.getIsBidirectional() != null
						&& castOther.getIsBidirectional() != null && this
						.getIsBidirectional().equals(
								castOther.getIsBidirectional())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInferredRelation() == null ? 0 : this
						.getInferredRelation().hashCode());
		result = 37 * result
				+ (getRelation1() == null ? 0 : this.getRelation1().hashCode());
		result = 37 * result
				+ (getRelation2() == null ? 0 : this.getRelation2().hashCode());
		result = 37
				* result
				+ (getIsBidirectional() == null ? 0 : this.getIsBidirectional()
						.hashCode());
		return result;
	}

}
