package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * RelationChain generated by hbm2java
 */
public class RelationChain implements java.io.Serializable {

	private RelationChainId id;

	public RelationChain() {
	}

	public RelationChain(RelationChainId id) {
		this.id = id;
	}

	public RelationChainId getId() {
		return this.id;
	}

	public void setId(RelationChainId id) {
		this.id = id;
	}

}
