package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubclassOfId generated by hbm2java
 */
public class SubclassOfId implements java.io.Serializable {

	private String cls;
	private String superCls;
	private String ontology;

	public SubclassOfId() {
	}

	public SubclassOfId(String cls, String superCls, String ontology) {
		this.cls = cls;
		this.superCls = superCls;
		this.ontology = ontology;
	}

	public String getCls() {
		return this.cls;
	}

	public void setCls(String cls) {
		this.cls = cls;
	}

	public String getSuperCls() {
		return this.superCls;
	}

	public void setSuperCls(String superCls) {
		this.superCls = superCls;
	}

	public String getOntology() {
		return this.ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubclassOfId))
			return false;
		SubclassOfId castOther = (SubclassOfId) other;

		return ((this.getCls() == castOther.getCls()) || (this.getCls() != null
				&& castOther.getCls() != null && this.getCls().equals(
				castOther.getCls())))
				&& ((this.getSuperCls() == castOther.getSuperCls()) || (this
						.getSuperCls() != null
						&& castOther.getSuperCls() != null && this
						.getSuperCls().equals(castOther.getSuperCls())))
				&& ((this.getOntology() == castOther.getOntology()) || (this
						.getOntology() != null
						&& castOther.getOntology() != null && this
						.getOntology().equals(castOther.getOntology())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCls() == null ? 0 : this.getCls().hashCode());
		result = 37 * result
				+ (getSuperCls() == null ? 0 : this.getSuperCls().hashCode());
		result = 37 * result
				+ (getOntology() == null ? 0 : this.getOntology().hashCode());
		return result;
	}

}
