package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 5:17:06 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubclassOfMapping generated by hbm2java
 */
public class SubclassOfMapping implements java.io.Serializable {

	private SubclassOfMappingId id;
	private Cls clsByCls;
	private Cls clsBySuperCls;

	public SubclassOfMapping() {
	}

	public SubclassOfMapping(SubclassOfMappingId id, Cls clsByCls,
			Cls clsBySuperCls) {
		this.id = id;
		this.clsByCls = clsByCls;
		this.clsBySuperCls = clsBySuperCls;
	}

	public SubclassOfMappingId getId() {
		return this.id;
	}

	public void setId(SubclassOfMappingId id) {
		this.id = id;
	}

	public Cls getClsByCls() {
		return this.clsByCls;
	}

	public void setClsByCls(Cls clsByCls) {
		this.clsByCls = clsByCls;
	}

	public Cls getClsBySuperCls() {
		return this.clsBySuperCls;
	}

	public void setClsBySuperCls(Cls clsBySuperCls) {
		this.clsBySuperCls = clsBySuperCls;
	}

}
