package org.geneontology.gold.hibernate.model;

// Generated Oct 22, 2010 9:25:51 AM by Hibernate Tools 3.4.0.Beta1

/**
 * SubclassOf generated by hbm2java
 */
public class SubclassOf implements java.io.Serializable {

	private SubclassOfId id;

	public SubclassOf() {
	}

	public SubclassOf(SubclassOfId id) {
		this.id = id;
	}

	public SubclassOfId getId() {
		return this.id;
	}

	public void setId(SubclassOfId id) {
		this.id = id;
	}

}
