package org.geneontology.gold.hibernate.model;

// Generated Nov 4, 2010 4:36:17 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubclassOf generated by hbm2java
 */
public class SubclassOf extends GOModel implements java.io.Serializable {


	private String ontology;
	private String cls;
	private String superCls;
	
	private Ontology ontologyObject;
	private Cls clsObject;
	private Cls superClsObject;
	
	public SubclassOf() {
	}

	public SubclassOf(String ontology, String superCls,
			String cls) {

		this.cls = cls;
		this.superCls = superCls;
		this.ontology = ontology;
		
		String[] uniqueConstraintFields = {"cls", "superCls", "ontology"};
		this.initUniqueConstraintFields(SubclassOf.class, uniqueConstraintFields);
	}
	
	
	


	public String getOntology() {
		return ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public String getCls() {
		return cls;
	}

	public void setCls(String cls) {
		this.cls = cls;
	}

	public String getSuperCls() {
		return superCls;
	}

	public void setSuperCls(String superCls) {
		this.superCls = superCls;
	}

	
	public Cls getClsObject() {
		if(clsObject == null && clsObject != null){
			clsObject = (Cls) getHibernateObject(Cls.class, "id", getCls());			
		}
		
		return clsObject;
	}

	public Ontology getOntologyObject() {
		if(ontologyObject == null && ontology != null){
			ontologyObject =(Ontology) getHibernateObject(Ontology.class, "id", this.ontology);
		}
		
		return ontologyObject;
	}
	
	public Cls getSuperClsObject() {
		if(superClsObject == null && superCls != null){
			superClsObject = (Cls) getHibernateObject(Cls.class, "id", superCls);
		}
		
		return superClsObject;
	}
	
	
}
