package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubclassOf generated by hbm2java
 */
public class SubclassOf implements java.io.Serializable {

	private SubclassOfId id;
	private Cls clsByCls;
	private Cls clsBySuperCls;

	public SubclassOf() {
	}

	public SubclassOf(SubclassOfId id, Cls clsByCls, Cls clsBySuperCls) {
		this.id = id;
		this.clsByCls = clsByCls;
		this.clsBySuperCls = clsBySuperCls;
	}

	public SubclassOfId getId() {
		return this.id;
	}

	public void setId(SubclassOfId id) {
		this.id = id;
	}

	public Cls getClsByCls() {
		return this.clsByCls;
	}

	public void setClsByCls(Cls clsByCls) {
		this.clsByCls = clsByCls;
	}

	public Cls getClsBySuperCls() {
		return this.clsBySuperCls;
	}

	public void setClsBySuperCls(Cls clsBySuperCls) {
		this.clsBySuperCls = clsBySuperCls;
	}

}
