package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 12:18:56 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubrelationOf generated by hbm2java
 */
public class SubrelationOf implements java.io.Serializable {

	private SubrelationOfId id;

	public SubrelationOf() {
	}

	public SubrelationOf(SubrelationOfId id) {
		this.id = id;
	}

	public SubrelationOfId getId() {
		return this.id;
	}

	public void setId(SubrelationOfId id) {
		this.id = id;
	}

}
