package org.geneontology.gold.hibernate.model;

// Generated Nov 2, 2010 3:53:51 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SubrelationOfId generated by hbm2java
 */
public class SubrelationOfId implements java.io.Serializable {

	private String relation;
	private String superRelation;
	private String ontology;

	public SubrelationOfId() {
	}

	public SubrelationOfId(String relation, String superRelation,
			String ontology) {
		this.relation = relation;
		this.superRelation = superRelation;
		this.ontology = ontology;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getSuperRelation() {
		return this.superRelation;
	}

	public void setSuperRelation(String superRelation) {
		this.superRelation = superRelation;
	}

	public String getOntology() {
		return this.ontology;
	}

	public void setOntology(String ontology) {
		this.ontology = ontology;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubrelationOfId))
			return false;
		SubrelationOfId castOther = (SubrelationOfId) other;

		return ((this.getRelation() == castOther.getRelation()) || (this
				.getRelation() != null && castOther.getRelation() != null && this
				.getRelation().equals(castOther.getRelation())))
				&& ((this.getSuperRelation() == castOther.getSuperRelation()) || (this
						.getSuperRelation() != null
						&& castOther.getSuperRelation() != null && this
						.getSuperRelation()
						.equals(castOther.getSuperRelation())))
				&& ((this.getOntology() == castOther.getOntology()) || (this
						.getOntology() != null
						&& castOther.getOntology() != null && this
						.getOntology().equals(castOther.getOntology())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRelation() == null ? 0 : this.getRelation().hashCode());
		result = 37
				* result
				+ (getSuperRelation() == null ? 0 : this.getSuperRelation()
						.hashCode());
		result = 37 * result
				+ (getOntology() == null ? 0 : this.getOntology().hashCode());
		return result;
	}

}
